### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by paddor** [brianmario/bzip2-ruby#2]
I'd love to use this library, but without _any_ documentation, it's totally useless.
[This](http://moulon.inra.fr/ruby/bz2.html) doesn't help either because, for example, Bzip2.new and .open are private in your library.

Can you provide documentation?
Thank you.

**Comment by brianmario** [comment]
Hi Patrik,
This project was just a fork of Guy Decoux's original called bz2. I only made patches for 1.9 compat and a couple of other minor things. I haven't modified the source other than that from it's original form so if the existing docs are out of date compared to my sources, they're also out of date for the most recent release of his original gem.

That being said, if I get any free time I'll do my best to document what's there as it stands today.

**Comment by bronson** [comment]
Agreed, the lack of docs is a major problem.

otoh, it appears to be pretty similar to Zlib:

```
def ungzip(file)
    Zlib::GzipReader.open(file) { |gz| yield(gz) }
end

def unbzip2(file)
    Bzip2::Reader.open(file) { |bz| yield(bz) }
end
```

**Comment by brianmario** [comment]
alexcrichton has done an excellent job finishing up some documentation throughout the gem, please re-open a new issue if you need something specific documented. Check out http://rubydoc.info/github/brianmario/bzip2-ruby/master/frames
