### ISSUE TITLE
Unable to build 0.2.7 on Ubuntu Natty Alpha 1

### ISSUE THREAD

**Issue by colindean** [brianmario/bzip2-ruby#6]
<pre>[colin@bricktop plas]$ gem install bzip2-ruby
Building native extensions.  This could take a while...
ERROR:  Error installing bzip2-ruby:
    ERROR: Failed to build gem native extension.

/home/colin/.rvm/rubies/ruby-head/bin/ruby extconf.rb
checking for bzlib.h... yes
checking for BZ2_bzWriteOpen() in -lbz2... yes
creating Makefile

make
compiling bzip2.c
bzip2.c: In function ‘bz_next_available’:
bzip2.c:779:18: warning: operation on ‘bzf->buf’ may be undefined
bzip2.c: In function ‘bz_reader_ungetc’:
bzip2.c:981:18: warning: operation on ‘bzf->buf’ may be undefined
bzip2.c: In function ‘bz_reader_ungets’:
bzip2.c:1025:18: warning: operation on ‘bzf->buf’ may be undefined
bzip2.c: In function ‘Init_bzip2_ext’:
bzip2.c:1726:5: error: ISO C90 forbids mixed declarations and code
make: *** [bzip2.o] Error 1

Gem files will remain installed in /home/colin/.rvm/gems/ruby-head@plas/gems/bzip2-ruby-0.2.7 for inspection.
Results logged to /home/colin/.rvm/gems/ruby-head@plas/gems/bzip2-ruby-0.2.7/ext/gem_make.out</pre>

`gem install bzip2-ruby --version 0.2.6` works fine for me.

Versions:
<pre>
[colin@bricktop plas]$ gem --version
1.3.7
[colin@bricktop plas]$ ruby --version
ruby 1.9.3dev (2010-12-18 trunk 30244) [x86_64-linux]
[colin@bricktop plas]$ dpkg --list | grep bz2
ii  libbz2-1.0                                1.0.5-6                                    high-quality block-sorting file compressor library - runtime
ii  libbz2-dev                                1.0.5-6                                    high-quality block-sorting file compressor library - development
[colin@bricktop plas]$ lsb_release -dr
Description:    Ubuntu natty (development branch)
Release:    11.04
</pre>

**Comment by brianmario** [comment]
tracking using #7 since it has the pull request attached

**Comment by brianmario** [comment]
oops, meant to close this too
